### ISSUE TITLE
superclass mismatch for class ToSql

### ISSUE THREAD

**Issue by pankas87** [fiksu/partitioned#70]
Hi, I'm trying to setup this gem on an existing proyect.

I have a Layer model that has_many Features, I'd like to partition the features by layer_id. Both table already exist and have rows stored.

I use PostgreSQL with PostGIS and the Postgis Active Record adapter.

After adding the `partiotioned` gem in my Gemfile and running `bundle install`, whenever I run any Rails command (console, generate migration, server, etc) I get the following error

````
/home/pankas87/.rvm/gems/ruby-2.2.0/gems/activerecord-redshift-adapter-0.9.12/lib/monkeypatch_arel.rb:73:in `<module:Visitors>': superclass mismatch for class ToSql (TypeError)
	from /home/pankas87/.rvm/gems/ruby-2.2.0/gems/activerecord-redshift-adapter-0.9.12/lib/monkeypatch_arel.rb:72:in `<module:Arel>'
	from /home/pankas87/.rvm/gems/ruby-2.2.0/gems/activerecord-redshift-adapter-0.9.12/lib/monkeypatch_arel.rb:71:in `<top (required)>'
	from /home/pankas87/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /home/pankas87/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/pankas87/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/pankas87/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /home/pankas87/.rvm/gems/ruby-2.2.0/gems/activerecord-redshift-adapter-0.9.12/lib/activerecord_redshift_adapter.rb:4:in `<top (required)>'
	from /home/pankas87/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /home/pankas87/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/pankas87/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/pankas87/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /home/pankas87/.rvm/gems/ruby-2.2.0/gems/partitioned-1.3.4/lib/monkey_patch_redshift.rb:5:in `<top (required)>'
	from /home/pankas87/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /home/pankas87/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/pankas87/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/pankas87/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /home/pankas87/.rvm/gems/ruby-2.2.0/gems/partitioned-1.3.4/lib/partitioned.rb:3:in `<top (required)>'
	from /home/pankas87/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
	from /home/pankas87/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /home/pankas87/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
	from /home/pankas87/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `block in require'
	from /home/pankas87/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
	from /home/pankas87/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
	from /home/pankas87/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
	from /home/pankas87/ruby-projects/wm20/config/application.rb:7:in `<top (required)>'
	from /home/pankas87/.rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:141:in `require'
	from /home/pankas87/.rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:141:in `require_application_and_environment!'
	from /home/pankas87/.rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:67:in `console'
	from /home/pankas87/.rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/pankas87/.rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
````

Any clue to what might be wrong? Is there any way that I can help?

**Comment by pankas87** [comment]
Following down the call stack, the problem seems to be here

https://github.com/fiksu/activerecord-redshift-adapter/blob/master/lib/monkeypatch_arel.rb

In line 73

**Comment by pankas87** [comment]
Checking out the original arel repo, looks like you are inheriting from the wrong superclass.

https://github.com/rails/arel/blob/master/lib/arel/visitors/to_sql.rb

In your monkey patch it extends:

````Arel::Visitors::ToSql < Arel::Visitors::Visitor````

But in the original code it extends

````Arel::Visitors::Reduce````

**Comment by pankas87** [comment]
I'll cose this one, it was fixed by @dkhofer in this PR

https://github.com/fiksu/partitioned/pull/67

So far is working good on a production system.

**Comment by grantchen** [comment]
@pankas87 I'm also use the @dkhofer PR version, but  i still have the same error, my rails versions is 4.2.6, Any suggestion for me? Thanks

```ruby
gem "partitioned", github: "dkhofer/partitioned", branch: "rails-4-2"
```

**Comment by pankas87** [comment]
This is a shortened version of the Gemfile I'm using

````
source 'https://rubygems.org'
ruby '2.2.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.1'

gem 'activerecord-redshift-adapter', :git => 'https://github.com/arp/activerecord-redshift-adapter', :branch => 'rails4-compatibility'
gem 'partitioned', :git => 'https://github.com/dkhofer/partitioned', :branch => 'rails-4-2'
````
